---
- name: restart traefik
  community.docker.docker_compose_v2:
    project_src: "{{ (docker.remote_dir, 'traefik') | path_join }}"
    state: present
    recreate: always
  listen: restart traefik
